#define FLOW_TAP_TERM 100
#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_TIMEOUT 185
#define SERIAL_NUMBER "zPWar/qmy9oK"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

